puts "🌱 Seeding data..."

User.create(first_name: "FN User1", last_name: "LN User1", email: "user1@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 5)
User.create(first_name: "FN User2", last_name: "LN User2", email: "user2@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 4)
User.create(first_name: "FN User3", last_name: "LN User3", email: "user3@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 3)
User.create(first_name: "FN User4", last_name: "LN User4", email: "user4@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 2)
User.create(first_name: "FN User5", last_name: "LN User5", email: "user5@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 1)
User.create(first_name: "FN User6", last_name: "LN User6", email: "user6@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 2)
User.create(first_name: "FN User7", last_name: "LN User7", email: "user7@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 3)
User.create(first_name: "FN User8", last_name: "LN User8", email: "user8@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 4)
User.create(first_name: "FN User9", last_name: "LN User9", email: "user9@google.com", password: "qwertyu", confirm_password: "qwertyu", trainer_id: 5)

Trainer.create(trainer_name: "Trainer1", job_title: "Trainer1 JD", specialization: "Weights")
Trainer.create(trainer_name: "Trainer2", job_title: "Trainer2 JD", specialization: "Bone Structure")
Trainer.create(trainer_name: "Trainer3", job_title: "Trainer3 JD", specialization: "Healthy Diet")
Trainer.create(trainer_name: "Trainer4", job_title: "Trainer4 JD", specialization: "Cycling")
Trainer.create(trainer_name: "Trainer5", job_title: "Trainer5 JD", specialization: "Belly Reduction")

Review.create(user_id: 1, review: "Review for user 1 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 2, review: "Review for user 2 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 3, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 4, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 5, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 6, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 7, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 8, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 9, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 9, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 9, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 1, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")
Review.create(user_id: 1, review: "Review for user 22 > ;klsx;ksmx;kkjnj lkms;kjnck klnx;kjn xlknxkjn kjxn;kjnx")

Appointment.create(user_id: 1, workout: "Bike riding, press ups", date: 9/11/22, duration: "2 hours", trainer_id: 1)
Appointment.create(user_id: 2, workout: "Bike riding, press ups", date: 4/11/22, duration: "1 hours", trainer_id: 5)
Appointment.create(user_id: 3, workout: "Bike riding, press ups", date: 4/11/22, duration: "2 hours", trainer_id: 4)
Appointment.create(user_id: 4, workout: "Bike riding, press ups", date: 4/11/22, duration: "1 hours", trainer_id: 3)
Appointment.create(user_id: 5, workout: "Bike riding, press ups", date: 4/11/22, duration: "3 hours", trainer_id: 2)
Appointment.create(user_id: 6, workout: "Bike riding, press ups", date: 4/11/22, duration: "4 hours", trainer_id: 2)
Appointment.create(user_id: 7, workout: "Bike riding, press ups", date: 4/11/22, duration: "3 hours", trainer_id: 1)
Appointment.create(user_id: 8, workout: "Bike riding, press ups", date: 4/11/22, duration: "6 hours", trainer_id: 4)
Appointment.create(user_id: 9, workout: "Bike riding, press ups", date: 4/11/22, duration: "3 hours", trainer_id: 5)
Appointment.create(user_id: 9, workout: "Bike riding, press ups", date: 4/11/22, duration: "1 hours", trainer_id: 2)
Appointment.create(user_id: 8, workout: "Bike riding, press ups", date: 4/11/22, duration: "2 hours", trainer_id: 3)
Appointment.create(user_id: 2, workout: "Bike riding, press ups", date: 4/11/22, duration: "2 hours", trainer_id: 5)
Appointment.create(user_id: 1, workout: "Bike riding, press ups", date: 4/11/22, duration: "5 hours", trainer_id: 3)
Appointment.create(user_id: 1, workout: "Bike riding, press ups", date: 4/11/22, duration: "1 hours", trainer_id: 2)
Appointment.create(user_id: 4, workout: "Bike riding, press ups", date: 4/11/22, duration: "4 hours", trainer_id: 1)

Contact.create(name: "John Doe", email: "email@email.com", phone: "+2445679877", message: "as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).")

puts "🌱 Done seeding!"
